"""empty message

Revision ID: b5079e86be12
Revises: bede0e6f644a
Create Date: 2024-09-19 17:30:50.260014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5079e86be12'
down_revision = 'bede0e6f644a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_macro_totals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_macro_totals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('total_protein', sa.FLOAT(), nullable=True),
    sa.Column('total_carbs', sa.FLOAT(), nullable=True),
    sa.Column('total_fats', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
